// Generated by EmDash on dev server start
// Do not edit manually

/// <reference types="emdash/locals" />

import type { ContentBylineCredit, PortableTextBlock } from "emdash";

export interface Coupon {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  description: string;
  discount_amount: string;
  code?: string;
  valid_from?: string;
  valid_until?: string;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

export interface CtaSection {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  description?: string;
  button_text: string;
  button_link?: string;
  phone_number?: string;
  background_image?: { id: string; src?: string; alt?: string; width?: number; height?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown> };
  style?: string;
  page?: string;
  display_order?: number;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

export interface Faq {
  id: string;
  slug: string | null;
  status: string;
  question: string;
  answer: string;
  category?: string;
  is_popular?: boolean;
  display_order?: number;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

export interface FinancingOption {
  id: string;
  slug: string | null;
  status: string;
  name: string;
  description: string;
  features?: unknown;
  apr?: string;
  terms_conditions?: string;
  logo?: { id: string; src?: string; alt?: string; width?: number; height?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown> };
  apply_url?: string;
  is_active: boolean;
  display_order?: number;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

export interface HeroSection {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  subtitle?: string;
  description?: string;
  background_image?: { id: string; src?: string; alt?: string; width?: number; height?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown> };
  primary_button_text?: string;
  primary_button_link?: string;
  secondary_button_text?: string;
  secondary_button_link?: string;
  features?: unknown;
  page: string;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

export interface Location {
  id: string;
  slug: string | null;
  status: string;
  name: string;
  description: string;
  address?: string;
  phone?: string;
  email?: string;
  service_area?: string;
  map_embed_url?: string;
  featured_image?: { id: string; src?: string; alt?: string; width?: number; height?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown> };
  services_offered?: unknown;
  why_choose_us?: unknown;
  is_active?: boolean;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

export interface MaintenancePlan {
  id: string;
  slug: string | null;
  status: string;
  name: string;
  price: string;
  description?: string;
  features: unknown;
  is_popular?: boolean;
  button_text?: string;
  display_order?: number;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

export interface Page {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  content?: PortableTextBlock[];
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

export interface PortfolioProject {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  description: string;
  full_description?: string;
  featured_image: { id: string; src?: string; alt?: string; width?: number; height?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown> };
  category: string;
  location?: string;
  completed_date?: string;
  client?: string;
  project_scope?: unknown;
  is_featured?: boolean;
  display_order?: number;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

export interface Post {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  featured_image?: { id: string; src?: string; alt?: string; width?: number; height?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown> };
  content?: PortableTextBlock[];
  excerpt?: string;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

export interface ProcessStep {
  id: string;
  slug: string | null;
  status: string;
  step_number: number;
  title: string;
  description: string;
  icon?: string;
  display_order?: number;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

export interface Service {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

export interface SiteSettings {
  id: string;
  slug: string | null;
  status: string;
  site_name: string;
  tagline?: string;
  logo?: { id: string; src?: string; alt?: string; width?: number; height?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown> };
  phone: string;
  email: string;
  address?: string;
  business_hours?: string;
  emergency_phone?: string;
  license_number?: string;
  facebook_url?: string;
  instagram_url?: string;
  linkedin_url?: string;
  twitter_url?: string;
  yelp_url?: string;
  meta_title?: string;
  meta_description?: string;
  cta_text?: string;
  cta_phone?: string;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

export interface Stat {
  id: string;
  slug: string | null;
  status: string;
  label: string;
  value: string;
  suffix?: string;
  icon?: string;
  display_order?: number;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

export interface TeamMember {
  id: string;
  slug: string | null;
  status: string;
  name: string;
  position: string;
  bio?: string;
  photo?: { id: string; src?: string; alt?: string; width?: number; height?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown> };
  certifications?: unknown;
  years_experience?: number;
  specialties?: unknown;
  display_order?: number;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

export interface Testimonial {
  id: string;
  slug: string | null;
  status: string;
  customer_name: string;
  rating: number;
  testimonial_text: string;
  location?: string;
  service_type?: string;
  date?: string;
  is_verified?: boolean;
  is_featured?: boolean;
  display_order?: number;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

declare module "emdash" {
  interface EmDashCollections {
    coupons: Coupon;
    cta_sections: CtaSection;
    faqs: Faq;
    financing_options: FinancingOption;
    hero_sections: HeroSection;
    locations: Location;
    maintenance_plans: MaintenancePlan;
    pages: Page;
    portfolio: PortfolioProject;
    posts: Post;
    process_steps: ProcessStep;
    services: Service;
    site_settings: SiteSettings;
    stats: Stat;
    team: TeamMember;
    testimonials: Testimonial;
  }
}